baseURL = 'https://chasej.dev/'
languageCode = 'en-us'
title = 'Chase Johnson'
theme = "cactus"

[params]
    description = """\
    Welcome to my blog! I'm a Computer Science PhD student at the University of \
    Minnesota with a particular interest in programming languages."""
    mainSection = "posts"
    mainSectionTitle = "Blog"
    showAllPostsOnHomePage = false
    postsOnHomePage = 5
    tocInline = true
    showProjectsList = true
    projectsUrl = "https://github.com/cjohnson19"
    mathjax = true
    showReadTime = true

[[params.social]]
    name = "github"
    link = "https://github.com/cjohnson19"

[[params.social]]
    name = "mastodon"
    link = "https://types.pl/@cjohnson"

[[params.social]]
    name = "email"
    link = "mail@chasej.dev"

[[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/chase-johnson19/"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "dracula"
    tabWidth = 4
